### ISSUE TITLE
Meteor 1.3.3 beta0 compatibility

### ISSUE THREAD

**Issue by priezz** [Meteor-Community-Packages/meteor-postcss#18]
I am not sure if it is `meteor-postcss` issue, but I have the following output, when trying to build:

```
» meteor build ./.build --directory --architecture os.linux.x86_64
...
Errors prevented bundling:
While loading plugin `minifier-postcss` from package `juliancwirko:postcss`:
<runJavaScript-37>:57:8: Object [object Object] has no method 'existsSync'
at meteorInstall.node_modules.meteor.minifier-postcss.plugin.minify-css.js (<runJavaScript-37>:57:8)
at fileEvaluate (packages/modules-runtime.js:158:9)
at require (packages/modules-runtime.js:92:16)
at <runJavaScript-37>:289:1
at <runJavaScript-37>:295:3
```

**Comment by juliancwirko** [comment]
yes it was [removed](https://github.com/meteor/meteor/commit/355e850829ec00024f62024f05bf622015056bbc) I probably need to delete this check

**Comment by juliancwirko** [comment]
It should work now in version 1.1.1

**Comment by priezz** [comment]
It works! You should probably change your nick to "rocket-man" or similar :)  Thanks for being so fast!
