### ISSUE TITLE
Errors when execting meteor test

### ISSUE THREAD

**Issue by namirsab** [Meteor-Community-Packages/meteor-postcss#26]
When I execute `meteor test` inside an app with this package, i get this error:

```
TypeError: Object [object Object] has no method 'await'
    at Object.wrapper [as realpath] (/tools/fs/files.js:1359:32)
    at SymlinkLoopChecker.check (/tools/isobuild/package-source.js:208:28)
    at find (/tools/isobuild/package-source.js:1453:23)
    at PackageSource._findSources (/tools/isobuild/package-source.js:1510:12)
    at SourceArch.getFiles (/tools/isobuild/package-source.js:1202:16)
    at /tools/isobuild/compiler.js:394:23
    at /tools/isobuild/compiler.js:176:26
    at Array.forEach (native)
    at Function._.each._.forEach (/home/namir_sayed_ahmad_baraza/.meteor/packages/meteor-tool/.1.3.2_4.tjz3e8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/tools/isobuild/compiler.js:171:5)
    at /tools/isobuild/isopack-cache.js:356:30
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:311:18)
    at /tools/isobuild/isopack-cache.js:245:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:244:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:235:20)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:209:12)
    at /tools/isobuild/isopack-cache.js:237:11
    at Array.forEach (native)
    at Function._.each._.forEach (/home/namir_sayed_ahmad_baraza/.meteor/packages/meteor-tool/.1.3.2_4.tjz3e8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack-cache.js:236:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:235:20)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:209:12)
    at /tools/isobuild/isopack-cache.js:237:11
    at Array.forEach (native)
    at Function._.each._.forEach (/home/namir_sayed_ahmad_baraza/.meteor/packages/meteor-tool/.1.3.2_4.tjz3e8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack-cache.js:236:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:235:20)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:209:12)
    at /tools/isobuild/isopack-cache.js:237:11
    at Array.forEach (native)
    at Function._.each._.forEach (/home/namir_sayed_ahmad_baraza/.meteor/packages/meteor-tool/.1.3.2_4.tjz3e8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack-cache.js:236:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:235:20)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:209:12)
    at /tools/isobuild/isopack-cache.js:237:11
    at Array.forEach (native)
    at Function._.each._.forEach (/home/namir_sayed_ahmad_baraza/.meteor/packages/meteor-tool/.1.3.2_4.tjz3e8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack-cache.js:236:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:235:20)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:209:12)
    at /tools/isobuild/isopack-cache.js:237:11
    at Array.forEach (native)
    at Function._.each._.forEach (/home/namir_sayed_ahmad_baraza/.meteor/packages/meteor-tool/.1.3.2_4.tjz3e8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack-cache.js:236:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:235:20)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/home/namir_sayed_ahmad_baraza/.meteor/packages/meteor-tool/.1.3.2_4.tjz3e8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object].eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:758:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._buildLocalPackages (/tools/project-context.js:757:18)
    at /tools/project-context.js:278:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (/tools/project-context.js:268:18)
    at /tools/project-context.js:260:12
    at Function.run (/tools/tool-env/profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (/tools/project-context.js:259:13)
    at /tools/runners/run-app.js:557:29
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundleApp (/tools/runners/run-app.js:556:31)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```

**Comment by juliancwirko** [comment]
Hi, which version of Meteor?

**Comment by copleykj** [comment]
Closing due to inactivity
